name: ai4cyber
channels: [conda-forge, defaults]
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - seaborn
  - joblib
  - xgboost
  - lightgbm
  - streamlit
  - optuna
  - pip
